### ISSUE TITLE
do not create swap on instances without ephemeral drives

### ISSUE THREAD

**Issue by rshade** [rightscale-cookbooks/rs-base#42]
@cdwilhelm reported we should not create swap on ebs volumes. Lets not do that. 
Thinking an instance_type guard might work: `%w(T2 M4).each`

**Comment by cdwilhelm** [comment]
I don't think we should do this.  the should should be able to decide if they want swap or not.  I think they can by setting the attributes

**Comment by cdwilhelm** [comment]
if we have an instance_type guard, then we have to maintain it for all the clouds.
